### ISSUE TITLE
Sprites optimization

### ISSUE THREAD

**Issue by pstupka** [pstupka/scribble-cars#17]
City sprites - much large with lots of transparency - change it to:
- single houses with various color variations
- atlas of windows textures for city?

Others
- cut sprites resolution with VisualServer.texture_set_shrink_all_x2_on_set_data(true) - possible setting
- Figure out how to batch
- Change sprites to 2D meshes

**Comment by pstupka-tivo** [comment]
- Resize huge city sprites
- Check every scene for possible sprites optimization
